/**
 * Types for the optional LLM narrative enrichment layer.
 *
 * These types describe the AI-generated narrative fragments
 * that SUPPLEMENT (never replace) the deterministic narrative.
 *
 * The LLM layer receives already-computed results as input
 * and returns only prose. It never recalculates or modifies
 * engine outputs.
 */

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

export interface LLMConfig {
  /** OpenAI-compatible API endpoint (e.g. https://api.openai.com/v1/chat/completions) */
  apiUrl: string;
  /** API key — stored only in browser memory, never persisted */
  apiKey: string;
  /** Model identifier (e.g. gpt-4o-mini) */
  model: string;
  /** Max tokens for each completion (mapped to max_tokens in the API request) */
  maxTokens: number;
  /** Temperature (0 = deterministic-ish, 1 = creative) */
  temperature: number;
}

export const DEFAULT_LLM_CONFIG: Omit<LLMConfig, 'apiKey'> = {
  apiUrl: 'https://api.openai.com/v1/chat/completions',
  model: 'gpt-4o-mini',
  maxTokens: 1024,
  temperature: 0.4,
};

// ---------------------------------------------------------------------------
// Enrichment results
// ---------------------------------------------------------------------------

/** AI-enriched argument for a stakeholder regarding an option. */
export interface EnrichedArgument {
  stakeholderId: string;
  optionId: string;
  type: 'support' | 'objection' | 'concession';
  text: string;
}

/** AI-enriched round summary prose. */
export interface EnrichedRoundNarrative {
  round: number;
  text: string;
}

/** The complete set of AI enrichments for a simulation. */
export interface LLMEnrichment {
  /** One enriched argument per stakeholder (brief argument for their preferred option) */
  stakeholderArguments: EnrichedArgument[];
  /** Brief objections per round (one per stakeholder who objects) */
  roundObjections: EnrichedArgument[];
  /** Enriched concession descriptions */
  concessionTexts: EnrichedArgument[];
  /** AI-generated executive summary */
  executiveSummary: string;
  /** Round-level narrative enrichments */
  roundNarratives: EnrichedRoundNarrative[];
  /** Whether enrichment was generated by AI or is a fallback */
  source: 'ai' | 'fallback';
  /** Error message if AI call failed */
  error?: string;
}

/** Empty enrichment object returned when AI is disabled or fails. */
export function emptyEnrichment(): LLMEnrichment {
  return {
    stakeholderArguments: [],
    roundObjections: [],
    concessionTexts: [],
    executiveSummary: '',
    roundNarratives: [],
    source: 'fallback',
  };
}

// ---------------------------------------------------------------------------
// Enrichment input (data passed to the LLM — all already computed)
// ---------------------------------------------------------------------------

export interface EnrichmentInput {
  scenarioName: string;
  companyName: string;
  scenarioDescription: string;
  /** Stakeholder summaries (id, name, role, mission, top priorities) */
  stakeholders: {
    id: string;
    name: string;
    role: string;
    mission: string;
    topPriorities: string[];
    style: { argumentative: string; concession: string };
  }[];
  /** Options with name and description */
  options: { id: string; name: string; description: string }[];
  /** The winning option name (already decided by engine) */
  winnerName: string;
  winnerId: string;
  /** Consensus status (already computed) */
  consensusStatus: string;
  /** Brief list of concessions (already computed) */
  concessions: {
    round: number;
    stakeholderName: string;
    stakeholderId: string;
    fromOption: string;
    toOption: string;
  }[];
  /** Vetoes (already computed) */
  vetoes: { stakeholderName: string; optionName: string; reason: string }[];
  /** Round summaries from the deterministic narrative */
  roundSummaries: { round: number; deterministicText: string }[];
  /** Deterministic headline and explanation */
  deterministicHeadline: string;
  deterministicExplanation: string;
}
